title: "zli.wang"
description: "Create, share, advance together."
baseurl: ""
url: "https://zli.wang"
github_username: "zhengliw"

author:
  name: "Zhengli Wang"
  email: "zhengliw@zli.wang"

minima:
  social_links:
    - title: GitHub
      icon: github
      url: "https://github.com/zhengliw/"

theme: minima
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag

paginate: 10

# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
